### ISSUE TITLE
Compat with Universal Graves

### ISSUE THREAD

**Issue by Panderine** [chronosacaria/SaveGearOnDeath#2] opened 2022-01-21 19:18 UTC
Hi!, 

I'm using https://www.curseforge.com/minecraft/mc-mods/universal-graves with fabri 1.18.1  and  graves is removing everthing from my hotbar, so It seems it takes precedence over SGOD. I don't really know if I should report this here or to Universal Graves. I guess both?.  Can you have a look at it pleaseeeeeeee :D

Thanks!!!

**Comment by chronosacaria** [comment] 2022-01-21 19:23
SGOD is not intended to be played with a grave mod. If it is taking precedence over SGOD, then it is functioning as intended. As such, I shall close this issue.

**Closed as completed by chronosacaria** 2022-01-21 19:23 UTC
